addons:
  chrome: stable
services:
  - xvfb
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
script:
  - npm run lint
  - npm run lint:dts
  - npm test
  - npm run test:server:coverage
  - npm run build
after_success:
  - npm run coveralls
notifications:
  email: false
