language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run dtslint
  - npm run test:coverage
after_success:
  - npm run coveralls
notifications:
  email: false
